In [18]:
# imports
%matplotlib inline

import time
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.formula.api as sm
import seaborn as sns #seaborn produces pretty nice graphs!
from scipy import stats
from sklearn.metrics import accuracy_score
from sklearn import svm
from sklearn.linear_model import LinearRegression
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from scipy.stats.stats import pearsonr
from statsmodels.graphics.regressionplots import abline_plot

In [19]:
events = pd.read_csv(r"\\ausemsmttp.aus.amer.dell.com\mlproject\EventsV4.csv")
events

,Id,Subject,EventTypeId,StatusId,SeverityId,ImpactTypeId,Escalation,NotifyMajorIncidentManagement,IncludeAllSegmentsApplications,PlannedStartDateTimeUtc,...,PlannedCompleteDateTimeUtc,ActualCompleteDateTimeUtc,Actual-StartPlan,Start_DateTime,Completed_DateTime+1day,Window_days,IncsCount,IncsPerDday,Start_Date,Completed_Date
0,8996,GTM upgrade 6.4.2 on GE2,1,3,3,2,0,0,0,2/7/2018,...,2/14/2018,2/14/2018,0,2/7/2018,2/15/2018,8.687500,1177,135.482014,2/7/2018,2/16/2018
1,8997,February MS / Linux Patching - Non-Prod - GE3 ...,1,3,3,1,0,0,1,2/19/2018,...,2/20/2018,2/21/2018,#VALUE!,2/19/2018,2/22/2018,2.359028,483,204.745363,2/19/2018,2/23/2018
2,8998,"February MS / Linux Patching - Non-Prod - GE1,...",1,3,3,1,0,0,1,2/26/2018,...,2/27/2018,3/1/2018,#VALUE!,2/26/2018,3/2/2018,3.363194,949,282.172207,2/26/2018,3/3/2018
3,8999,Sabrix GE4 5.3 Down,1,3,3,2,0,0,0,2/7/2018,...,2/7/2018,2/7/2018,#VALUE!,2/7/2018,2/8/2018,1.015278,130,128.043776,2/7/2018,2/9/2018
4,9001,GE1 ENV SERVICE IS AVAILABLE PATCHING COMPLE...,1,3,3,2,0,0,0,2/12/2018,...,2/12/2018,NaN,#VALUE!,2/12/2018,2/13/2018,1.041667,158,151.680000,2/12/2018,2/14/2018
5,9002,Delta DB TLS Enablement for SIT (GE2),1,3,3,2,0,0,0,2/17/2018,...,2/17/2018,2/17/2018,#VALUE!,2/17/2018,2/18/2018,1.291667,136,105.290323,2/17/2018,2/19/2018
6,9003,Batch testing for Flex Billing,1,3,3,1,0,0,0,2/15/2018,...,2/15/2018,2/16/2018,0.000430127,2/15/2018,2/17/2018,1.345833,138,102.538700,2/15/2018,2/18/2018
7,9004,Domino - AUSUWS1DMSG03 - Ping Down,2,3,2,1,0,0,1,2/20/2018,...,2/20/2018,2/20/2018,0,2/20/2018,2/21/2018,1.040972,176,169.072715,2/20/2018,2/22/2018
8,9005,Paritioning ITEMCAT,2,3,2,1,0,0,0,2/20/2018,...,2/20/2018,2/20/2018,0,2/20/2018,2/21/2018,1.098611,191,173.855879,2/20/2018,2/22/2018
9,9006,Glovia All instances GE1 DB Refresh from Prod ...,1,3,3,2,0,0,0,2/26/2018,...,3/2/2018,3/9/2018,1.121527778,2/27/2018,3/10/2018,10.955556,2643,241.247464,2/27/2018,3/11/2018
10,9007,February MS / Linux Patching - Non-Prod - GE4 ...,1,3,3,1,0,0,1,2/28/2018,...,3/1/2018,3/9/2018,0.250917014,3/1/2018,3/10/2018,9.056250,2220,245.134576,3/1/2018,3/11/2018
11,9008,**Agile Global Enviornment 2 - Venus will be d...,1,3,3,2,0,0,0,2/27/2018,...,2/28/2018,3/2/2018,#VALUE!,2/27/2018,3/3/2018,3.947222,901,228.261787,2/27/2018,3/4/2018
12,9009,Domino GE1 DB Down,2,3,2,1,0,1,1,2/27/2018,...,2/27/2018,2/27/2018,0,2/27/2018,2/28/2018,1.291667,333,257.806452,2/27/2018,3/1/2018
13,9011,CHG0130319-Optimizing/Re-Structuring Non-Prod ...,1,3,3,1,0,0,1,3/5/2018,...,3/8/2018,3/8/2018,0,3/5/2018,3/9/2018,4.250000,1150,270.588235,3/5/2018,3/10/2018
14,9012,FY19Q1 GE3 SIT Data Refresh,1,3,3,1,0,0,0,3/18/2018,...,3/21/2018,3/21/2018,0,3/18/2018,3/22/2018,3.784722,1833,484.315596,3/18/2018,3/23/2018
15,9013,Sabrix down for refresh on GE1,1,3,3,2,0,0,0,3/5/2018,...,3/5/2018,3/5/2018,0.116863461,3/5/2018,3/6/2018,1.039583,332,319.358717,3/5/2018,3/7/2018
16,9014,FY18R1 release patch retrofit for Oracle Apps ...,1,3,3,2,0,0,0,3/5/2018,...,3/6/2018,3/6/2018,#VALUE!,3/5/2018,3/7/2018,1.166667,330,282.857143,3/5/2018,3/8/2018
17,9015,GE3 Tandem Data Refresh,1,3,3,2,0,0,1,3/19/2018,...,3/21/2018,3/21/2018,-0.491281979,3/18/2018,3/22/2018,3.970833,1916,482.518363,3/18/2018,3/23/2018
18,9016,Synchro - DB Refresh SYNG4S,1,3,3,2,0,0,1,3/19/2018,...,3/23/2018,3/27/2018,2.481389965,3/21/2018,3/28/2018,6.595139,3213,487.177003,3/21/2018,3/29/2018
19,9017,SYNCHRO - DB Refresh - SYPER,1,3,3,2,0,0,1,3/12/2018,...,3/16/2018,3/21/2018,#VALUE!,3/12/2018,3/22/2018,10.264583,4328,421.644003,3/12/2018,3/23/2018
20,9018,RR2C Storage Issue - Multiple Ping Down!!!,2,3,2,1,1,1,1,3/13/2018,...,3/13/2018,3/13/2018,0,3/13/2018,3/14/2018,1.187500,477,401.684211,3/13/2018,3/15/2018
21,9019,Config Staging DB Migration to SQL 2016,1,3,3,2,0,0,0,3/16/2018,...,3/16/2018,3/16/2018,0.104615475,3/16/2018,3/17/2018,1.104167,390,353.207547,3/16/2018,3/18/2018
22,9020,Delta DB TLS Enablement for SIT (GE2),1,3,3,2,0,0,0,3/13/2018,...,3/13/2018,3/13/2018,#VALUE!,3/13/2018,3/14/2018,1.000000,391,391.000000,3/13/2018,3/15/2018
23,9021,Most of the Omega/Gii non prod Databases are d...,2,3,2,1,0,0,0,3/14/2018,...,3/14/2018,3/14/2018,0,3/14/2018,3/15/2018,1.136806,439,386.169823,3/14/2018,3/16/2018
24,9022,AX2012 SQL Database Server Drives Missing - IN...,2,3,2,1,0,0,0,3/14/2018,...,3/14/2018,3/14/2018,0,3/14/2018,3/15/2018,1.127778,428,379.507389,3/14/2018,3/16/2018
25,9023,March MS / Linux Patching - Non-Prod - GE3 - P...,1,3,3,1,0,0,1,3/19/2018,...,3/20/2018,3/30/2018,0.148379595,3/20/2018,3/31/2018,11.450694,5349,467.133240,3/20/2018,4/1/2018
26,9024,CHG0130876 - APAC-MAINTENANCE-NR-DT-MYACYB BUI...,1,3,3,1,0,0,0,3/17/2018,...,3/18/2018,3/18/2018,0,3/17/2018,3/19/2018,2.541667,490,192.786885,3/17/2018,3/20/2018
27,9025,SYNQA - SYNCHRO Database is down,2,3,2,1,0,0,1,3/19/2018,...,3/19/2018,3/26/2018,0,3/19/2018,3/27/2018,8.111111,4168,513.863014,3/19/2018,3/28/2018
28,9026,FY19Q1 GE4 Product Data Refresh,1,3,3,1,0,0,1,4/8/2018,...,4/11/2018,4/11/2018,0.784027778,4/9/2018,4/12/2018,3.195139,2215,693.240600,4/9/2018,4/13/2018
29,9027,"FY19 - Oracle Security Patch - GE2, GE3, PERF1...",1,3,3,1,0,0,1,3/31/2018,...,4/1/2018,4/1/2018,0.000627546,3/31/2018,4/2/2018,2.583333,1057,409.161290,3/31/2018,4/3/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,9194,"December MS / Linux Patching - Non-Prod - GE1,...",1,3,3,1,0,0,1,12/24/2018,...,12/25/2018,1/7/2019,0.148676354,12/25/2018,1/8/2019,14.331944,2882,201.089253,12/25/2018,1/9/2019
175,9195,SYNCHRO GE2 - Retrofit,1,3,3,2,0,0,0,12/28/2018,...,12/31/2018,2/18/2019,0.0555439,12/28/2018,2/19/2019,53.032639,12451,234.779944,12/28/2018,2/20/2019
176,9196,FY19Q4 GE3 Product Data Refresh,1,3,3,1,0,0,0,1/28/2019,...,1/29/2019,1/29/2019,0,1/28/2019,1/30/2019,2.833333,1450,511.764706,1/28/2019,1/31/2019
177,9197,January MS / Linux Patching - Non-Prod - GE3 -...,1,3,3,1,0,0,1,1/15/2019,...,1/16/2019,1/21/2019,0.040551354,1/15/2019,1/22/2019,6.095139,1529,250.855645,1/15/2019,1/23/2019
178,9198,Feb Release Omega patching - GE2 - Down Time,1,3,3,2,0,0,0,1/8/2019,...,1/9/2019,1/9/2019,#VALUE!,1/8/2019,1/10/2019,1.229167,448,364.474576,1/8/2019,1/11/2019
179,9199,January MS Patching - Non-Prod - GE2 & PERF - ...,1,3,3,1,0,0,1,1/20/2019,...,1/21/2019,1/23/2019,0,1/20/2019,1/24/2019,3.705556,1093,294.962519,1/20/2019,1/25/2019
180,9200,FY19Q4 GE4 Product Data Refresh,1,3,3,1,0,0,0,1/21/2019,...,1/22/2019,1/23/2019,0,1/21/2019,1/24/2019,3.208333,1000,311.688312,1/21/2019,1/25/2019
181,9201,January MS Patching - Non-Prod - GE1 & GE4- No...,1,3,3,1,0,0,1,1/22/2019,...,1/23/2019,2/13/2019,0.090952859,1/23/2019,2/14/2019,22.365278,5742,256.737254,1/23/2019,2/15/2019
182,9202,GE1 & GE4 SDR Migration to Physical Servers,1,3,3,1,0,0,1,1/22/2019,...,1/22/2019,1/22/2019,#VALUE!,1/22/2019,1/23/2019,1.100000,483,439.090909,1/22/2019,1/24/2019
183,9203,QMS Down Time on GE2 for 0203 Release,1,3,3,2,0,0,0,1/24/2019,...,1/24/2019,1/24/2019,#VALUE!,1/24/2019,1/25/2019,1.041667,222,213.120000,1/24/2019,1/26/2019
184,9204,Oracle BRM - Service Account Password Rest - ...,1,3,3,2,0,0,0,1/28/2019,...,1/28/2019,1/28/2019,#VALUE!,1/28/2019,1/29/2019,1.132639,278,245.444513,1/28/2019,1/30/2019
185,9205,omega G1 enviornment will be down to perfor...,1,1,3,1,0,0,1,2/6/2019,...,2/6/2019,NaN,#VALUE!,2/6/2019,2/7/2019,1.250000,379,303.200000,2/6/2019,2/8/2019
186,9206,Enablement of oracle spatial feature for SDR,1,1,3,1,0,0,1,2/6/2019,...,2/6/2019,2/6/2019,#VALUE!,2/6/2019,2/7/2019,1.083333,391,360.923077,2/6/2019,2/8/2019
187,9207,Omega GE2 is Down,2,3,1,1,0,0,0,2/8/2019,...,2/8/2019,2/8/2019,0,2/8/2019,2/9/2019,1.020139,216,211.735875,2/8/2019,2/10/2019
188,9208,SYNHRO - GE1 - Install Preparation,1,3,3,2,0,0,0,2/12/2019,...,2/13/2019,2/18/2019,-0.006944444,2/12/2019,2/19/2019,7.384028,2250,304.711746,2/12/2019,2/20/2019
189,9209,February MS & Linux Patching - Non-Prod - GE1 ...,1,3,3,1,0,0,1,2/20/2019,...,2/21/2019,2/24/2019,0.354154363,2/21/2019,2/25/2019,3.929167,1895,482.290562,2/21/2019,2/26/2019
190,9210,Missing Disks on VMs on R2CCT2,2,3,2,1,0,0,0,2/13/2019,...,2/14/2019,2/17/2019,0,2/13/2019,2/18/2019,5.050694,1567,310.254366,2/13/2019,2/19/2019
191,9211,SYNCHRO - GE4 - Install Preparation,2,3,2,1,0,0,0,2/13/2019,...,2/14/2019,2/18/2019,0,2/13/2019,2/19/2019,6.126389,1919,313.235094,2/13/2019,2/20/2019
192,9212,Oracle PSU 2019 Patch On Non-Prod Environments,1,3,3,1,0,0,1,2/23/2019,...,2/24/2019,2/24/2019,0,2/23/2019,2/25/2019,2.636806,1235,468.369766,2/23/2019,2/26/2019
193,9213,Test Event for Mobile application,2,3,1,1,0,0,1,2/19/2019,...,2/19/2019,2/21/2019,0,2/19/2019,2/22/2019,3.059722,1157,378.138902,2/19/2019,2/23/2019
194,9214,"OSB,BPEL,BPM & BAM domains Patching for GOBIG...",1,1,3,2,0,0,1,2/20/2019,...,2/20/2019,2/20/2019,#VALUE!,2/20/2019,2/21/2019,1.083333,614,566.769231,2/20/2019,2/22/2019
195,9215,Omega GE4 down for Appl cutover and grid/db pa...,1,3,3,1,0,0,0,2/20/2019,...,2/20/2019,2/20/2019,-0.000709109,2/20/2019,2/21/2019,1.154167,623,539.783393,2/20/2019,2/22/2019
196,9216,"February MS & Linux Patching - Non-Prod - GE2,...",1,3,3,1,0,0,1,2/23/2019,...,2/24/2019,2/24/2019,0.283140475,2/24/2019,2/25/2019,0.884028,313,354.061273,2/24/2019,2/26/2019
197,9217,GE1 Linux Servers Reboot - Kernel Upgrade,1,3,3,1,0,0,1,2/22/2019,...,2/23/2019,2/23/2019,-0.017142014,2/22/2019,2/24/2019,1.350694,947,701.120823,2/22/2019,2/25/2019
198,9218,Oracle PSU 2019 Patch On Non-Prod Environments...,1,3,3,1,0,0,1,3/9/2019,...,3/10/2019,3/10/2019,1.717181215,3/10/2019,3/11/2019,0.950000,338,355.789474,3/10/2019,3/12/2019
199,9219,"Sabrix Downtime GE2, GE4 & PERF",1,3,3,2,0,0,0,2/28/2019,...,2/28/2019,2/28/2019,0.016666667,2/28/2019,3/1/2019,1.108333,353,318.496241,2/28/2019,3/2/2019
200,9220,GAFT-GE4 Database Migration To New MDC DB Servers,1,3,3,2,0,0,0,3/4/2019,...,3/4/2019,3/4/2019,#VALUE!,3/4/2019,3/5/2019,1.254167,601,479.202658,3/4/2019,3/6/2019
201,9221,FY20Q1 GE2 Product Data Refresh,1,3,3,1,0,0,0,3/11/2019,...,3/12/2019,3/14/2019,2.502816238,3/13/2019,3/15/2019,1.909028,625,327.391779,3/13/2019,3/16/2019
202,9222,S3B Maintenance - Non-Prod Environment Impacts,1,3,3,2,0,0,0,3/10/2019,...,3/10/2019,3/10/2019,0,3/10/2019,3/11/2019,1.666667,721,432.600000,3/10/2019,3/12/2019
203,9223,Omega GE2 downtime,1,3,3,2,0,0,0,3/6/2019,...,3/6/2019,3/6/2019,0.001080058,3/6/2019,3/7/2019,1.057639,792,748.837820,3/6/2019,3/8/2019

In [43]:
# TODO: select only "SalePrice", "Bedrooms", "Bathrooms", "SqFtTotLiving", "SqFtLot"
events_small = events[["EventTypeId","ImpactTypeId", "IncsCount"]]
events_small

     EventTypeId  ImpactTypeId  IncsCount
0              1             2       1177
1              1             1        483
2              1             1        949
3              1             2        130
4              1             2        158
5              1             2        136
6              1             1        138
7              2             1        176
8              2             1        191
9              1             2       2643
10             1             1       2220
11             1             2        901
12             2             1        333
13             1             1       1150
14             1             1       1833
15             1             2        332
16             1             2        330
17             1             2       1916
18             1             2       3213
19             1             2       4328
20             2             1        477
21             1             2        390
22             1             2        391
23             2             1        439
24             2             1        428
25             1             1       5349
26             1             1        490
27             2             1       4168
28             1             1       2215
29             1             1       1057
..           ...           ...        ...
174            1             1       2882
175            1             2      12451
176            1             1       1450
177            1             1       1529
178            1             2        448
179            1             1       1093
180            1             1       1000
181            1             1       5742
182            1             1        483
183            1             2        222
184            1             2        278
185            1             1        379
186            1             1        391
187            2             1        216
188            1             2       2250
189            1             1       1895
190            2             1       1567
191            2             1       1919
192            1             1       1235
193            2             1       1157
194            1             2        614
195            1             1        623
196            1             1        313
197            1             1        947
198            1             1        338
199            1             2        353
200            1             2        601
201            1             1        625
202            1             2        721
203            1             2        792

[204 rows x 3 columns]

In [47]:
#TESTING DATA PREPARATION

## TODO : input cols : gre, gpa, rank
fv = events_small[['EventTypeId', 'ImpactTypeId']].values
labels = events_small['IncsCount'].values


X_train, X_test, Y_train, Y_test = train_test_split(events_small[['EventTypeId', 'ImpactTypeId']], labels, test_size=0.2)
print("training set = " , len(X_train))
print("testing set = " , len(Y_test))

training set =  163
testing set =  41

In [48]:
clf = svm.SVC(kernel='linear')

t1 = time.perf_counter()
clf.fit(X_train, Y_train)
t2 = time.perf_counter()


print("trained on {:,} records in {:,.2f} ms".\
      format(len(X_train), (t2-t1)*1000))

# Print the coefficients and intercept for linearsSVC
print ("inputs : EventTypeId, ImpactTypeId, IncsCount")

trained on 163 records in 84.47 ms
inputs : EventTypeId, ImpactTypeId, IncsCount

In [49]:
predictions = clf.predict(X_test)
predictions

array([1393, 1393, 1393, 1895,  546,  546,  546,  546,  546,  546, 1393,
       1393, 1895, 1895,  546, 3234, 1393, 1393, 1393, 1895, 1393,  546,
       1393,  546, 1393, 1393, 1393,  546, 1895, 1895, 1393, 1393,  546,
       1393, 1895, 1895, 1393,  546, 1895, 1393,  546], dtype=int64)

In [50]:
print("Accuracy = " + str(accuracy_score(Y_test, predictions)))

Accuracy = 0.0